### ISSUE TITLE
Could you create a "SASSless" version?

### ISSUE THREAD

**Issue by oneezy** [marcinkrzeminski/gulp-starter-kit#1]
I prefer to use normal `CSS` and make use of the _Sass like_ features that we're getting.

I'm trying to remove the `Sass` stuff right now but it's a bit confusing for me.

**Comment by marcinkrzeminski** [comment]
Hi @oneezy 

I just pushed the code you asked for into the sassless branch. In order to use it just clone the repo and switch the branch.

```
git clone https://github.com/marcinkrzeminski/gulp-starter-kit.git
cd gulp-starter-kit
git checkout sassless
npm install
gulp // for dev
gulp build // build for prod
```

Let me know if you have any other questions ;)

**Comment by oneezy** [comment]
Awesome! Thanks a ton
